import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}


//  <h2 className="text-4xl md:text-5xl font-light tracking-wide text-gray-700 flex items-center justify-center gap-2">
//             <Sparkles className="text-yellow-400" size={32} /> Alomonx Excellence
//           </h2>
//           <p className="text-lg text-gray-500 mt-4 max-w-2xl mx-auto leading-relaxed">
//             Click a service to explore how Alomonx outshines the competition with innovative, tailored solutions.
//           </p>
